### ISSUE TITLE
oauth2.0 logging out user

### ISSUE THREAD

**Issue by johnjwatson** [demianbrecht/django-sanction#1]
I am trying to integrate django-sanction into my blog app (django newbie here), but I seem not to be able to "logout" the user after the login process (using Google OAuth2.0).

The entire process seems pain free - i.e I am able to get all user details on my db, and able to access user details on my django templates, but, when I logout and try to log back in, it seems to remember my credentials (cookies?). I am trying to logout from here: [https://github.com/demianbrecht/django-sanction/blob/master/example/example/templates/profile.html]

p.s: I am developing on localhost - wondering if this is the problem(?)

**Comment by demianbrecht** [comment]
I'm not entirely sure what you mean. Just so I understand your steps, you:
- Login
- Access user data (functions as expected)
- Logout
- Login again (?) and it remembers who you are

If that's the case, you may not be fully understanding how the OAuth 2.0 model works. If you're logged into Google already and you've already authorized the application, you will not see either a) the Google login page, or b) the authorization page. Google will automatically redirect you back to the website you're interacting with, with new OAuth 2.0 data. The only way that you'll see the authorization page again is if a) you remove authorization for your application through your Google account settings or b) change your password (maybe? I haven't tried that flow yet).

If that's not the path that you're following please let me know and I'll investigate further. If this _is_ the case, also please let me know so that I can close this issue.

**Comment by johnjwatson** [comment]
Hi Demian,

Thank you for the explanation - I think I get it - I had misunderstood the OAuth2.0 workflow. Your mentioned steps are exactly what I encounter. I was under the false impression that the "user" will get logged out of google as-well, when the user accesses: o/logout/

So, basically, the function:

def logout(request):
    django_logout(request)
    return redirect(getattr(settings, "OAUTH2_LOGOUT_REDIRECT_URL", "/"))
urlpatterns = patterns("",
    url(r"^logout/$", logout, name="oauth2-logout"), 
)

simply redirects: /o/logout/ to: /
Is my understanding correct? i.e no communication between user and google during this step. 
So, the user needs to logout from google to "log out" from the app requesting access.

I would like to thank you for the "dead simple" package! Using it is awesome.

**Comment by demianbrecht** [comment]
All logout does is clears the user cookie for the current site. In no way, shape or form can it log a user out of Google (doing so would involve modifying Google's cookies which is not allowed by user agents). You also can't log a user out of Google (AFAIK) through any exposed API.

Glad you're enjoying using the package :+1:
